# Site settings
title: neal.enssle.me
email: neal.enssle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog mostly about managing programmers, engineers, designers and technical types. By Neal Enssle.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nealenssle.com" # the base hostname & protocol for your site
twitter_username: nealenssle
github_username:  nealenssle

permalink: pretty

# Build settings
markdown: kramdown
